
USE PRIMEIRO_BD

UPDATE CLIENTE
SET EMAIL = 'CONTATO2@LEO.COM.BR'
WHERE ID_CLIENTE = 1

UPDATE CLIENTE
SET 
	NOME = 'LENOKINHO',
	EMAIL = 'L3NOK@GMAIL.COM'
WHERE 
	ID_CLIENTE = 1

SELECT TOP (1000) [ID_CLIENTE]
      ,[NOME]
      ,[DATA_CADASTRO]
      ,[EMAIL]
  FROM [PRIMEIRO_BD].[dbo].[CLIENTE]